version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - FRONTEND_URL=https://live-caption-eta.vercel.app
    env_file:
      - ./.env
    restart: always