const commonHinglishMap = {
    // --- PRONOUNS (सर्वनाम) ---
    "मैं": "main", "हम": "hum", "तुम": "tum", "आप": "aap", "वह": "woh", "यह": "yeh", "वे": "ve", "ये": "ye",
    "मेरा": "mera", "तुम्हारा": "tumhara", "आपका": "aapka", "हमारा": "hamara", "उसका": "uska", "इसका": "iska",
    "उनका": "unka", "इनका": "inka", "किसे": "kise", "किसको": "kisko", "किन्हें": "kinhein", "कौन": "kaun",
    "क्या": "kya", "क्यों": "kyun", "कब": "kab", "कहाँ": "kahan", "कैसे": "kaise", "कितना": "kitna",
    "किस": "kis", "किसका": "kiska", "कौन-सा": "kaunsa",

    // --- HELPING VERBS & TENSES ---
    "है": "hai", "हैं": "hain", "हूँ": "hoon", "था": "tha", "थी": "thi", "थे": "the",
    "गा": "ga", "गी": "gi", "गे": "ge",

    // --- CONJUNCTIONS & PREPOSITIONS ---
    "और": "aur", "या": "ya", "लेकिन": "lekin", "मगर": "magar", "पर": "par", "क्योंकि": "kyunki",
    "इसलिए": "isliye", "अगर": "agar", "तो": "toh", "की": "ki", "का": "ka", "के": "ke", "को": "ko",
    "ने": "ne", "से": "se", "में": "mein", "लिए": "liye", "द्वारा": "dwara", "तक": "tak",
    "साथ": "saath", "बिना": "bina", "पास": "paas", "दूर": "door", "ऊपर": "upar", "नीचे": "neeche",
    "अंदर": "andar", "बाहर": "bahar", "आगे": "aage", "पीछे": "peeche", "सामने": "saamne", "बीच": "beech",
    "इधर": "idhar", "उधर": "udhar", "यहाँ": "yahan", "वहाँ": "wahan", "जहाँ": "jahan", "दाएँ": "daayein",
    "बाएँ": "baayein", "शून्य": "shunya",// --- 11 to 20 ---
    "ग्यारह": "gyarah",
    "बारह": "baarah",
    "तेरह": "terah",
    "चौदह": "chaudah",
    "पंद्रह": "pandrah",
    "सोलह": "solah",
    "सत्रह": "satrah",
    "अठारह": "atharah",
    "उन्नीस": "unnees",
    "बीस": "bees",

    // --- 21 to 30 ---
    "इक्कीस": "ikkees",
    "बाईस": "baees",
    "तेईस": "teees",
    "चौबीस": "chaubees",
    "पच्चीस": "pachchees",
    "छब्बीस": "chhabbees",
    "सत्ताईस": "sattaees",
    "अट्ठाईस": "atthaees",
    "उनतीस": "unatees",
    "तीस": "tees",

    // --- 31 to 40 ---
    "इकतीस": "ikatees",
    "बत्तीस": "battees",
    "तैंतीस": "taintees",
    "चौंतीस": "chauntees",
    "पैंतीस": "paintees",
    "छत्तीस": "chattees",
    "सैंतीस": "saintees",
    "अड़तीस": "adatees",
    "उनतालीस": "unataalees",
    "चालीस": "chaalees",

    // --- 41 to 50 ---
    "इकतालीस": "iktaalees",
    "बयालीस": "bayaalees",
    "तैंतालीस": "taintaalees",
    "चवालीस": "chauvaalees",
    "पैंतालीस": "paintaalees",
    "छियालीस": "chiyaalees",
    "सैंतालीस": "saintalees",
    "अड़तालीस": "adtaalees",
    "उनचास": "unchaas",
    "पचास": "pachaas",

    // --- 51 to 60 ---
    "इक्यावन": "ikyaavan",
    "बावन": "baavan",
    "तिरेपन": "tirepan",
    "चौवन": "chauvan",
    "पचपन": "pachpan",
    "छप्पन": "chhappan",
    "सत्तावन": "sattavan",
    "अट्ठावन": "atthaavan",
    "उनसठ": "unsath",
    "साठ": "saath",

    // --- 61 to 70 ---
    "इकसठ": "iksath",
    "बासठ": "baasath",
    "तिरसठ": "tirsath",
    "चौंसठ": "chaunsath",
    "पैंसठ": "painsath",
    "छियासठ": "chiyasath",
    "सड़सठ": "sadsath",
    "अड़सठ": "adsath",
    "उनहत्तर": "unhattar",
    "सत्तर": "sattar",

    // --- 71 to 80 ---
    "इकहत्तर": "ikhattar",
    "बहत्तर": "bahattar",
    "तिहत्तर": "tihattar",
    "चौहत्तर": "chauhattar",
    "पचहत्तर": "pachhattar",
    "छिहत्तर": "chihattar",
    "सतहत्तर": "satahattar",
    "अठहत्तर": "athhattar",
    "उन्यासी": "unyaasi",
    "अस्सी": "assi",

    // --- 81 to 90 ---
    "इक्यासी": "ikyaasi",
    "बयासी": "bayaasi",
    "तिरासी": "tiraasi",
    "चौरासी": "chaurasi",
    "पचासी": "pachaasi",
    "छियासी": "chiyaasi",
    "सत्तासी": "sattaasi",
    "अट्ठासी": "atthaasi",
    "नवासी": "navaasi",
    "नब्बे": "nabbe",

    // --- 91 to 100 ---
    "इक्यानवे": "ikyaanve",
    "बानवे": "baanavve",
    "तिरानवे": "tiranve",
    "चौरानवे": "chauranve",
    "पचानवे": "pachanve",
    "छियानवे": "chiyanve",
    "सत्तानवे": "sattanve",
    "अट्ठानवे": "atthanve",
    "निन्यानवे": "ninyanve",
    "सौ": "sau",

    // --- Milestones ---
    "हजार": "hazaar",
    "लाख": "lakh",
    "करोड़": "crore",
    "अरब": "arab",
    "खरब": "kharab",

    // --- Ordinals (Rank) ---
    "पहला": "pehla",
    "दूसरा": "doosra",
    "तीसरा": "teesra",
    "चौथा": "chautha",
    "पांचवा": "paanchva",
    "छठा": "chhatha",
    "सातवा": "saatva",
    "आठवा": "aathva",
    "नौवा": "nauva",
    "दसवा": "dasva",
    "आखिरी": "aakhiri",
    "अंतिम": "antim",

    // --- Fractions/Quantities ---
    "आधा": "aadha",
    "पौना": "pauna",     // 3/4
    "सवा": "sava",       // 1.25 or +0.25
    "डेढ़": "dedh",      // 1.5
    "ढाई": "dhai",       // 2.5
    "साढ़े": "saadhe",


    // --- ACTION VERBS (क्रिया) ---
    "आना": "aana", "जाना": "jaana", "खाना": "khana", "पीना": "peena", "सोना": "sona", "जागना": "jaagna",
    "उठना": "uthna", "बैठना": "baithna", "चलना": "chalna", "दौड़ना": "daudna", "रुकना": "rukna",
    "देखना": "dekhna", "सुनना": "sunna", "बोलना": "bolna", "कहना": "kehna", "बताना": "batana",
    "पूछना": "poochna", "करना": "karna", "होना": "hona", "लेना": "lena", "देना": "dena",
    "लाना": "laana", "ले": "le", "भेजना": "bhejna", "बुलाना": "bulana", "समझना": "samajhna",
    "समझाना": "samjhana", "सोचना": "sochna", "जानना": "jaanna", "मानना": "maanna",
    "पहचानना": "pehchanna", "मिलना": "milna", "मिलाना": "milana", "ढूँढना": "dhoondhna",
    "खोना": "khona", "पाना": "paana", "जीतना": "jeetna", "हारना": "haarna", "पढ़ना": "padhna",
    "लिखना": "likhna", "सीखना": "seekhna", "सिखाना": "sikhana", "खेलना": "khelna", "कूदना": "koodna",
    "हँसना": "hasna", "रोना": "rona", "मुस्कुराना": "muskurana", "डरना": "darna", "घबराना": "ghabrana",
    "चिल्लाना": "chillana", "गुस्सा": "gussa", "मारना": "maarna", "पीटना": "peetna", "बचाना": "bachana",
    "मदद": "madad", "कोशिश": "koshish", "शुरू": "shuru", "खत्म": "khatam", "रोकना": "rokna",
    "काम": "kaam", "आराम": "aaraam", "नहाना": "nahana", "धोना": "dhona", "साफ": "saaf",
    "पकाना": "pakana", "बनाना": "banana", "तोड़ना": "todna", "जोड़ना": "jodna", "खरीदना": "kharidna",
    "बेचना": "bechna", "खर्च": "kharch", "चुराना": "churana", "झूठ": "jhoot", "सच": "sach",
    "वादा": "vaada", "भूलना": "bhoolna", "याद": "yaad", "प्यार": "pyaar", "नफरत": "nafrat", "शादी": "shaadi",

    // --- ADJECTIVES (विशेषण) ---
    "अच्छा": "accha", "बुरा": "bura", "खराब": "kharab", "सही": "sahi", "गलत": "galat", "नया": "naya",
    "पुराना": "purana", "गंदा": "ganda", "बदसूरत": "badsurat", "बड़ा": "bada", "छोटा": "chota",
    "लंबा": "lamba", "नाटा": "naata", "मोटा": "mota", "पतला": "patla", "भारी": "bhaari", "हल्का": "halka",
    "गरम": "garam", "ठंडा": "thanda", "गीला": "geela", "सूखा": "sookha", "तेज": "tez", "धीरे": "dheere",
    "आसान": "aasaan", "मुश्किल": "mushkil", "कठिन": "kathin", "महंगा": "mehenga", "सस्ता": "sasta",
    "अमीर": "ameer", "गरीब": "gareeb", "खुश": "khush", "दुखी": "dukhi", "उदास": "udaas",
    "नाराज": "naaraaz", "परेशान": "pareshaan", "बीमार": "beemar", "स्वस्थ": "swasth", "ठीक": "theek",
    "तैयार": "taiyar", "व्यस्त": "vyast", "खाली": "khaali", "अकेला": "akela", "पूरा": "poora",
    "आधा": "aadha", "थोड़ा": "thoda", "बहुत": "bahut", "ज्यादा": "zyada", "कम": "kam", "काफी": "kaafi",
    "बस": "bas", "लगभग": "lagbhag", "शायद": "shayad", "जरूर": "zaroor", "हमेशा": "hamesha",
    "कभी": "kabhi", "अक्सर": "aksar", "रोज": "roz",

    // --- TIME (समय) ---
    "अभी": "abhi", "बाद": "baad", "पहले": "pehle", "जल्दी": "jaldi", "देर": "der", "आज": "aaj",
    "कल": "kal", "परसों": "parso", "सुबह": "subah", "दोपहर": "dopahar", "शाम": "shaam",
    "रात": "raat", "दिन": "din", "हफ्ता": "hafta", "सप्ताह": "saptah", "महीना": "mahina",
    "साल": "saal", "वर्ष": "varsh", "समय": "samay", "वक्त": "waqt", "घड़ी": "ghadi",
    "घंटा": "ghanta", "मिनट": "minute", "पल": "pal", "बार": "baar", "तारीख": "tareekh",

    // --- OBJECTS, PLACES, NATURE ---
    "मौसम": "mausam", "धूप": "dhoop", "बारिश": "baarish", "बादल": "baadal", "हवा": "hawa",
    "तूफान": "toofan", "बिजली": "bijli", "सर्दी": "sardi", "गर्मी": "garmi", "पानी": "paani",
    "आग": "aag", "मिट्टी": "mitti", "आसमान": "aasman", "जमीन": "zameen", "दुनिया": "duniya",
    "देश": "desh", "शहर": "sheher", "गाँव": "gaon", "मकान": "makaan", "कमरा": "kamra", "छत": "chhat",
    "दरवाजा": "darwaza", "खिड़की": "khidki", "दीवार": "deewar", "फर्श": "farsh", "रसोई": "rasoi",
    "बाथरूम": "bathroom", "बिस्तर": "bistar", "कुर्सी": "kursi", "मेज": "mez", "गाड़ी": "gaadi",
    "रास्ता": "rasta", "सड़क": "sadak", "बाजार": "bazaar", "दुकान": "dukaan", "अस्पताल": "aspatal",
    "रुपये": "rupaye", "सिक्का": "sikka", "दाम": "daam", "भाव": "bhaav",

    // --- GREETINGS & BASICS ---
    "नमस्ते": "namaste", "प्रणाम": "pranaam", "शुक्रिया": "shukriya", "धन्यवाद": "dhanyavaad",
    "कृपया": "kripya", "माफ": "maaf", "स्वागत": "swagat", "बधाई": "badhai", "हाँ": "haan",
    "जी": "ji", "नहीं": "nahi", "ना": "na", "मत": "mat",

    // --- RELATIONS & PEOPLE ---
    "लोग": "log", "आदमी": "aadmi", "औरत": "aurat", "बच्चा": "bacha", "लड़का": "ladka",
    "लड़की": "ladki", "मित्र": "mitra", "दुश्मन": "dushman", "रिश्तेदार": "rishtedar",
    "मेहमान": "mehmaan", "परिवार": "parivaar", "माता": "mata", "पिता": "pita", "माँ": "maa",
    "पापा": "papa", "भाई": "bhai", "बहन": "behen", "बेटा": "beta", "बेटी": "beti", "पति": "pati",
    "पत्नी": "patni", "दादा": "dada", "दादी": "dadi", "नाना": "nana", "नानी": "nani",
    "चाचा": "chacha", "चाची": "chachi", "मामा": "mama", "मामी": "mami", "पड़ोसी": "padosi",
    "अध्यापक": "adhyapak", "छात्र": "chatra",

    // --- NUMBERS ---
    "एक": "ek", "दो": "do", "तीन": "teen", "चार": "chaar", "पाच": "paanch", "दस": "das",
    "बीस": "bees", "पचास": "pachaas", "सौ": "sau", "हजार": "hazaar", "लाख": "lakh", "करोड़": "crore",
    "पहला": "pehla", "दूसरा": "doosra", "तीसरा": "teesra", "आखिरी": "aakhiri", "सब": "sab",
    "कुछ": "kuch", "कोई": "koi", "हर": "har", "प्रत्येक": "pratyek", "अलग": "alag", "वही": "wahi",
    "ऐसा": "aisa", "वैसा": "waisa", "जैसा": "jaisa",
    // ==========================================
    // 1. VERB CONJUGATIONS (The most common spoken forms)
    // ==========================================

    // To Do (Karna)
    "करूँ": "karun", "करूँगा": "karunga", "करूँगी": "karungi", "करेंगे": "karenge",
    "करेगा": "karega", "करेगी": "karegi", "करो": "karo", "करिए": "kariye",
    "करते": "karte", "करती": "karti", "करता": "karta",
    "किया": "kiya", "किये": "kiye", "की": "ki",
    "करके": "karke", "करना": "karna", "करने": "karne",

    // To Be (Hona)
    "हूँ": "hoon", "हो": "ho", "होगा": "hoga", "होगी": "hogi", "होंगे": "honge",
    "हुआ": "hua", "हुई": "hui", "हुए": "hue", "होता": "hota", "होती": "hoti", "होते": "hote",
    "होने": "hone", "होकर": "hokar", "होना": "hona",

    // To Go (Jaana)
    "जाऊँ": "jaaun", "जाऊँगा": "jaunga", "जाऊँगी": "jaungi", "जाएंगे": "jayenge",
    "जाएगा": "jayega", "जाएगी": "jayegi", "जाओ": "jao", " जाइए": "jaiye",
    "जाता": "jaata", "जाती": "jaati", "जाते": "jaate",
    "गया": "gaya", "गई": "gayi", "गए": "gaye",
    "जाकर": "jakar", "जाने": "jaane",

    // To Come (Aana)
    "आऊँ": "aaun", "आऊँगा": "aaunga", "आऊँगी": "aaungi", "आएंगे": "aayenge",
    "आएगा": "aayega", "आएगी": "aayegi", "आओ": "aao", "आइए": "aaiye",
    "आता": "aata", "आती": "aati", "आते": "aate",
    "आया": "aaya", "आई": "aayi", "आए": "aaye",
    "आकर": "aakar", "आने": "aane",

    // To Give (Dena)
    "दूँ": "doon", "दूँगा": "doonga", "दूँगी": "doongi", "देंगे": "denge",
    "देगा": "dega", "देगी": "degi", "दो": "do", "दीजिए": "dijiye",
    "देता": "deta", "देती": "deti", "देते": "dete",
    "दिया": "diya", "दिए": "diye", "दी": "dee",
    "देकर": "dekar", "देने": "dene",

    // To Take (Lena)
    "लूँ": "loon", "लूँगा": "loonga", "लूँगी": "loongi", "लेंगे": "lenge",
    "लेगा": "lega", "लेगी": "legi", "लो": "lo", "लीजिए": "lijiye",
    "लेता": "leta", "लेती": "leti", "लेते": "lete",
    "लिया": "liya", "लिए": "liye", "ली": "lee",
    "लेकर": "lekar", "लेने": "lene",

    // To Say/Speak (Kehna/Bolna)
    "कहूँ": "kahun", "कहूँगा": "kahunga", "कहूँगी": "kahungi", "कहेंगे": "kahenge",
    "कहेगा": "kahega", "कहेगी": "kahegi", "कहो": "kaho", "कहिए": "kahiye",
    "कहता": "kehta", "कहती": "kehti", "कहते": "kehte",
    "कहा": "kaha", "कही": "kahi", "कहे": "kahe",
    "कहकर": "kehkar", "कहने": "kehne",
    "बोलूँगा": "bolunga", "बोलूँगी": "bolungi", "बोलेंगे": "bolenge",
    "बोला": "bola", "बोली": "boli", "बोले": "bole", "बोलकर": "bolkar", "बोलने": "bolne",

    // To See/Look (Dekhna)
    "देखूँ": "dekhun", "देखूँगा": "dekhunga", "देखूँगी": "dekhungi", "देखेंगे": "dekhenge",
    "देखेगा": "dekhega", "देखेगी": "dekhegi", "देखो": "dekho", "देखिए": "dekhiye",
    "देखता": "dekhta", "देखती": "dekhti", "देखते": "dekhte",
    "देखा": "dekha", "देखी": "dekhi", "देखे": "dekhe",
    "देखकर": "dekhkar", "देखने": "dekhne",

    // To Understand/Explain (Samajhna/Samjhana)
    "समझूँ": "samjhun", "समझूँगा": "samjhunga", "समझेंगे": "samjhenge",
    "समझा": "samjha", "समझी": "samjhi", "समझे": "samjhe",
    "समझता": "samajhta", "समझते": "samajhte", "समझकर": "samajhkar", "समझने": "samajhne",
    "समझाओ": "samjhao", "समझाया": "samjhaya",

    // To Ask (Puchna)
    "पूछूँ": "puchun", "पूछूँगा": "puchunga", "पूछेंगे": "puchenge",
    "पूछा": "pucha", "पूछी": "puchi", "पूछे": "puche",
    "पूछता": "puchta", "पूछते": "puchte", "पूछकर": "puchkar", "पूछने": "puchne",

    // To Think (Sochna)
    "सोचूँ": "sochun", "सोचूँगा": "sochunga", "सोचेंगे": "sochenge",
    "सोचा": "socha", "सोची": "sochi", "सोचे": "soche",
    "सोचता": "sochta", "सोचते": "sochte", "सोचकर": "sochkar", "सोचने": "sochne",

    // To Find/Meet (Milna)
    "मिलूँ": "milun", "मिलूँगा": "milunga", "मिलेंगे": "milenge",
    "मिला": "mila", "मिली": "mili", "मिले": "mile",
    "मिलता": "milta", "मिलते": "milte", "मिलकर": "milkar", "मिलने": "milne",

    // Continuous Tense Markers (Raha/Rahi)
    "रहा": "raha", "रही": "rahi", "रहे": "rahe",
    "चुका": "chuka", "चुकी": "chuki", "चुके": "chuke",
    "सका": "saka", "सकी": "saki", "सके": "sake",
    "पाया": "paaya", "पायी": "paayi", "पाए": "paaye",
    "लगा": "laga", "लगी": "lagi", "लगे": "lage", // e.g. karne laga (started doing)

    // ==========================================
    // 2. ENGLISH LOANWORDS (Written in Hindi Script)
    // These are CRITICAL for Speech-to-Text accuracy
    // ==========================================

    "टाइम": "time", "टेंशन": "tension", "प्रॉब्लम": "problem", "फ़ोन": "phone",
    "कॉल": "call", "मैसेज": "message", "नंबर": "number", "रिचार्ज": "recharge",
    "नेट": "net", "इंटरनेट": "internet", "वाईफाई": "wifi", "स्पीड": "speed",
    "ऑफिस": "office", "बॉस": "boss", "मीटिंग": "meeting", "स्टाफ": "staff",
    "स्कूल": "school", "कॉलेज": "college", "क्लास": "class", "टीचर": "teacher",
    "स्टूडेंट": "student", "एग्जाम": "exam", "पेपर": "paper", "रिजल्ट": "result",
    "पास": "pass", "फेल": "fail", "एडमिशन": "admission", "फीस": "fees",
    "डॉक्टर": "doctor", "हॉस्पिटल": "hospital", "नर्स": "nurse", "दवाई": "dawaai",
    "पेशेंट": "patient", "रिपोर्ट": "report", "टेस्ट": "test", "चेकअप": "checkup",
    "बस": "bus", "ट्रेन": "train", "फ्लाइट": "flight", "टिकट": "ticket",
    "सीट": "seat", "बुकिंग": "booking", "कैंसिल": "cancel", "लेट": "late",
    "ड्राइवर": "driver", "कंडक्टर": "conductor", "स्टेशन": "station", "स्टॉप": "stop",
    "मार्केट": "market", "शॉपिंग": "shopping", "मॉल": "mall", "ब्रांड": "brand",
    "डिस्काउंट": "discount", "ऑफर": "offer", "सेल": "sale", "प्राइस": "price",
    "रेट": "rate", "बिल": "bill", "कैश": "cash", "ऑनलाइन": "online",
    "बैंक": "bank", "अकाउंट": "account", "बैलेंस": "balance", "लोन": "loan",
    "क्रेडिट": "credit", "डेबिट": "debit", "कार्ड": "card", "पिन": "pin",
    "मूवी": "movie", "फिल्म": "film", "हीरो": "hero", "हीरोइन": "heroine",
    "सीन": "scene", "सॉन्ग": "song", "म्यूजिक": "music", "वीडियो": "video",
    "गेम": "game", "मैच": "match", "स्कोर": "score", "प्लेयर": "player",
    "टीम": "team", "विनर": "winner", "लूजर": "loser", "बैट": "bat", "बॉल": "ball",
    "लंच": "lunch", "डिनर": "dinner", "ब्रेकफास्ट": "breakfast", "पार्टी": "party",
    "होटल": "hotel", "रेस्टोरेंट": "restaurant", "मेन्यू": "menu", "ऑर्डर": "order",
    "टेस्टी": "tasty", "स्पाइसी": "spicy", "स्वीट": "sweet", "फ्रेश": "fresh",
    "लाइफ": "life", "लव": "love", "हेट": "hate", "फीलिंग": "feeling",
    "मूड": "mood", "वाइब": "vibe", "लक": "luck", "चांस": "chance",
    "आईडिया": "idea", "प्लान": "plan", "सक्सेस": "success", "फ्यूचर": "future",
    "जॉब": "job", "इंटरव्यू": "interview", "सैलरी": "salary", "कंपनी": "company",
    "लैपटॉप": "laptop", "कंप्यूटर": "computer", "माउस": "mouse", "कीबोर्ड": "keyboard",
    "स्क्रीन": "screen", "डिस्प्ले": "display", "बैटरी": "battery", "चार्जर": "charger",
    "लिंक": "link", "शेयर": "share", "लाइक": "like", "कमेंट": "comment",
    "पोस्ट": "post", "ब्लॉक": "block", "ग्रुप": "group", "स्टेटस": "status",
    "स्टोरी": "story", "रील": "reel", "वायरल": "viral", "ट्रेंड": "trend",
    "न्यूज़": "news", "चैनल": "channel", "एंकर": "anchor", "रिपोर्टर": "reporter",
    "पुलिस": "police", "कोर्ट": "court", "केस": "case", "जज": "judge",
    "वकील": "vakil", "लॉयर": "lawyer", "कानून": "kanoon", "रूल": "rule",
    "वोट": "vote", "इलेक्शन": "election", "नेता": "neta", "पार्टी": "party",
    "सिस्टम": "system", "सेटिंग": "setting", "अपडेट": "update", "इंस्टॉल": "install",
    "ऐप": "app", "सॉफ्टवेयर": "software", "हार्डवेयर": "hardware", "डेटा": "data",
    "फाइल": "file", "फोल्डर": "folder", "कॉपी": "copy", "पेस्ट": "paste",
    "डिलीट": "delete", "सेव": "save", "प्रिंट": "print", "स्कैन": "scan",
    "लाइट": "light", "फैन": "fan", "एसी": "ac", "कूलर": "cooler",
    "स्विच": "switch", "वायर": "wire", "प्लग": "plug", "मशीन": "machine",
    "रोड": "road", "ट्रैफिक": "traffic", "सिग्नल": "signal", "पार्किंग": "parking",
    "पेट्रोल": "petrol", "डीजल": "diesel", "गैस": "gas", "हवा": "hawa",
    "शर्ट": "shirt", "पेंट": "pant", "जींस": "jeans", "टीशर्ट": "t-shirt",
    "जूते": "joote", "शूज": "shoes", "चप्पल": "chappal", "सैंडल": "sandal",
    "बैग": "bag", "पर्स": "purse", "वॉलेट": "wallet", "बेल्ट": "belt",
    "घड़ी": "ghadi", "वॉच": "watch", "चश्मा": "chashma", "गोगल्स": "goggles",
    "स्टाइल": "style", "फैशन": "fashion", "मेकअप": "makeup", "लुक": "look",
    "सिंपल": "simple", "नॉर्मल": "normal", "स्पेशल": "special", "रेगुलर": "regular",
    "अर्जेंट": "urgent", "इंपॉर्टेंट": "important", "सीरियस": "serious", "मजाक": "mazaak",
    "शोर": "shor", "साइलेंस": "silence", "पीस": "peace", "वॉर": "war",

    // ==========================================
    // 3. EMOTIONS, NOUNS & ABSTRACT CONCEPTS
    // ==========================================
    "ज़िंदगी": "zindagi", "जीवन": "jeevan", "मौत": "maut", "मृत्यु": "mrityu",
    "सपना": "sapna", "हकीकत": "haqeeqat", "सच": "sach", "झूठ": "jhoot",
    "विश्वास": "vishwas", "भरोसा": "bharosa", "यकीन": "yakeen", "उम्मीद": "umeed",
    "आशा": "aasha", "निराशा": "niraasha", "धोखा": "dhokha", "वफा": "wafa",
    "हिम्मत": "himmat", "साहस": "saahas", "डर": "darr", "खौफ": "khauf",
    "इज्जत": "izzat", "सम्मान": "samman", "बेइज्जती": "beizzati", "अपमान": "apmaan",
    "शर्म": "sharam", "बेशर्म": "besharam", "घमंड": "ghamand", "अहंकार": "ahankaar",
    "किस्मत": "kismat", "भाग्य": "bhagya", "नसीब": "naseeb", "तकदीर": "taqdeer",
    "दुआ": "dua", "प्रार्थना": "prarthana", "बद्दुआ": "baddua", "श्राप": "shraap",
    "भगवान": "bhagwan", "ईश्वर": "ishwar", "अल्लाह": "allah", "खुदा": "khuda",
    "धर्म": "dharm", "मजहब": "mazhab", "जाति": "jaati", "समाज": "samaaj",
    "दुनिया": "duniya", "संसार": "sansaar", "जगत": "jagat", "विश्व": "vishwa",
    "त्योहार": "tyohar", "पर्व": "parv", "उत्सव": "utsav", "मेला": "mela",
    "शादी": "shaadi", "विवाह": "vivah", "मंगनी": "mangni", "सगाई": "sagai",
    "रिश्ता": "rishta", "नाता": "naata", "संबंध": "sambandh", "संपर्क": "sampark",
    "दोस्ती": "dosti", "यारी": "yaari", "दुश्मनी": "dushmani", "बैर": "bair",
    "प्यार": "pyaar", "प्रेम": "prem", "मोहब्बत": "mohabbat", "इश्क": "ishq",
    "नफरत": "nafrat", "घृणा": "ghrina", "क्रोध": "krodh", "गुस्सा": "gussa",
    "शांति": "shanti", "सुकून": "sukoon", "चैन": "chain", "बेचैनी": "bechaini",
    "खुशी": "khushi", "आनंद": "anand", "मज़ा": "maza", "लुत्फ": "lutf",
    "दुख": "dukh", "दर्द": "dard", "पीड़ा": "peeda", "तकलीफ": "takleef",
    "गम": "gham", "शोक": "shok", "मातम": "maatam", "उदासी": "udaasi",
    "मुसीबत": "musibat", "संकट": "sankat", "परेशानी": "pareshani", "समस्या": "samasya",
    "हल": "hal", "समाधान": "samadhan", "उपाय": "upaay", "तरीका": "tarika",
    "रास्ता": "raasta", "मार्ग": "marg", "दिशा": "disha", "मंजिल": "manzil",
    "सफर": "safar", "यात्रा": "yatra", "प्रवास": "pravas", "दौरा": "daura",
    "जगह": "jagah", "स्थान": "sthan", "ठिकाना": "thikana", "पता": "pata",
    "महत्व": "mahatva", "कीमत": "keemat", "मूल्य": "mulya", "दाम": "daam",
    "फायदा": "fayda", "लाभ": "laabh", "मुनाफा": "munafa", "बचत": "bachat",
    "नुकसान": "nuksaan", "हानि": "haani", "घाटा": "ghata", "बर्बादी": "barbaadi",
    "सफलता": "safalta", "कामयाबी": "kaamyabi", "जीत": "jeet", "विजय": "vijay",
    "असफलता": "asafalta", "नाकामयाबी": "naakaamyabi", "हार": "haar", "पराजय": "parajay",
    "कोशिश": "koshish", "प्रयास": "prayas", "प्रयत्न": "prayatna", "मेहनत": "mehnat",
    "आलस": "aalas", "सुस्ती": "susti", "थकान": "thakan", "नींद": "neend",
    "भूख": "bhookh", "प्यास": "pyaas", "इच्छा": "iccha", "ख्वाहिश": "khwahish",
    "आदत": "aadat", "लत": "lat", "शौक": "shauk", "जुनून": "junoon",
    "ताकत": "taakat", "शक्ति": "shakti", "बल": "bal", "जोर": "zor",
    "कमजोरी": "kamzori", "दुर्बलता": "durbalta", "बीमारी": "bimari", "रोग": "rog",
    "इलाज": "ilaaj", "उपचार": "upchaar", "सेहत": "sehat", "स्वास्थ्य": "swasthya",
    "दिमाग": "dimaag", "बुद्धि": "buddhi", "अक्ल": "akal", "समझ": "samajh",
    "याद": "yaad", "स्मृति": "smriti", "भूल": "bhool", "गलती": "galti",
    "माफी": "maafi", "क्षमा": "kshama", "सजा": "saza", "दंड": "dand",
    "इंसाफ": "insaaf", "न्याय": "nyay", "फैसला": "faisla", "निर्णय": "nirnay",
    "सवाल": "sawaal", "प्रश्न": "prashna", "जवाब": "jawab", "उत्तर": "uttar",
    "बहस": "behas", "विवाद": "vivaad", "झगड़ा": "jhagda", "लड़ाई": "ladai",
    "बात": "baat", "चर्चा": "charcha", "गुफ्तगू": "guftagu", "वार्तालाप": "vartalaap",
    "कहानी": "kahani", "किस्सा": "kissa", "दास्तान": "dastaan", "अफसाना": "afsaana",
    "कविता": "kavita", "शायरी": "shayari", "गीत": "geet", "गाना": "gaana",
    "रंग": "rang", "रूप": "roop", "शक्ल": "shakal", "सूरत": "surat",
    "शरीर": "shareer", "बदन": "badan", "तन": "tan", "काया": "kaaya",
    "आत्मा": "aatma", "रूह": "rooh", "मन": "mann", "दिल": "dil",

    // ==========================================
    // 4. COMMON ADJECTIVES & ADVERBS (Reddit/Daily)
    // ==========================================
    "शायद": "shayad", "ज़रूर": "zaroor", "पक्का": "pakka", "बिलकुल": "bilkul",
    "वाकई": "waaqai", "सचमुच": "sachmuch", "असल": "asal", "दरअसल": "darasal",
    "खास": "khaas", "विशेष": "vishesh", "मामूली": "maamuli", "साधारण": "saadharan",
    "अजीब": "ajeeb", "अनोखा": "anokha", "विचित्र": "vichitra", "अद्भुत": "adbhut",
    "बढ़िया": "badhiya", "बेहतर": "behtar", "बेहतरीन": "behtareen", "शानदार": "shaandaar",
    "खराब": "kharaab", "बेकार": "bekaar", "रद्दी": "raddi", "घटिया": "ghatiya",
    "मुश्किल": "mushkil", "कठिन": "kathin", "आसान": "aasaan", "सरल": "saral",
    "महंगा": "mehenga", "कीमती": "keemti", "सस्ता": "sasta", "मुफ्त": "muft",
    "भारी": "bhaari", "वजनी": "vazni", "हल्का": "halka", "थोड़ा": "thoda",
    "ज़्यादा": "zyada", "अधिक": "adhik", "काफी": "kaafi", "पर्याप्त": "paryaapt",
    "पूरा": "poora", "संपूर्ण": "sampurna", "आधा": "aadha", "अधूरा": "adhoora",
    "खाली": "khaali", "रिक्त": "rikt", "भरा": "bhara", "पूर्ण": "purna",
    "नया": "naya", "नवीन": "naveen", "पुराना": "purana", "प्राचीन": "pracheen",
    "ताज़ा": "taaza", "बासी": "baasi", "गरम": "garam", "ठंडा": "thanda",
    "साफ": "saaf", "स्वच्छ": "swachh", "गंदा": "ganda", "मैला": "maila",
    "सुंदर": "sundar", "खूबसूरत": "khoobsurat", "प्यारा": "pyaara", "आकर्षक": "aakarshak",
    "बदसूरत": "badsurat", "कुरूप": "kuroop", "डरावना": "daraavna", "भयानक": "bhayanak",
    "खुश": "khush", "प्रसन्न": "prasann", "दुखी": "dukhi", "उदास": "udaas",
    "नाराज़": "naaraaz", "गुस्सा": "gussa", "शांत": "shaant", "चुप": "chup",
    "तेज़": "tez", "तीव्र": "tivra", "धीरे": "dheere", "मंद": "mand",
    "ऊँचा": "ooncha", "लंबा": "lamba", "नीचा": "neecha", "छोटा": "chota",
    "मोटा": "mota", "पतला": "patla", "चौड़ा": "chauda", "संकरा": "sankara",
    "गहरा": "gehra", "उथला": "uthla", "गीला": "geela", "सूखा": "sookha",
    "अमीर": "ameer", "धनी": "dhani", "गरीब": "gareeb", "निर्धन": "nirdhan",
    "सच्चा": "saccha", "ईमानदार": "imaandaar", "झूठा": "jhootha", "बेईमान": "beimaan",
    "समझदार": "samajhdaar", "होशियार": "hoshiyaar", "चालाक": "chaalaak", "मूर्ख": "murkh",
    "पागल": "paagal", "दीवाना": "deewana", "बेवकूफ": "bewakoof", "बुद्धू": "buddhu",
    "बहादुर": "bahadur", "वीर": "veer", "डरपोक": "darpok", "कायर": "kaayar",
    "दयालु": "dayalu", "रहमदिल": "rehamdil", "क्रूर": "kroor", "जालिम": "zaalim",
    "प्यारा": "pyaara", "लाडला": "laadla", "अकेला": "akela", "तनहा": "tanha",
    "व्यस्त": "vyast", "बिजी": "busy", "मुक्त": "mukt", "फ्री": "free",
    "तैयार": "taiyar", "रेडी": "ready", "उपलब्ध": "uplabdh", "मौजूद": "maujood",
    "गायब": "gayab", "नदारद": "nadaarad", "प्रसिद्ध": "prasiddh", "मशहूर": "mashhoor",
    "अज्ञात": "agyaat", "गुमनाम": "gumnaam", "गुप्त": "gupt", "खुला": "khula",
    "बंद": "band", "लॉक": "lock", "सही": "sahi", "गलत": "galat",
    "उचित": "uchit", "अनुचित": "anuchit", "योग्य": "yogya", "अयोग्य": "ayogya",
    "संभव": "sambhav", "मुमकिन": "mumkin", "असंभव": "asambhav", "नामुमकिन": "namumkin",
    "आवश्यक": "aavashyak", "ज़रूरी": "zaroori", "अनिवार्य": "anivarya", "वैकल्पिक": "vaikalpik",
    "स्वादिष्ट": "swadisht", "लज़ीज़": "lazeez", "फीका": "feeka", "कड़वा": "kadwa",
    "मीठा": "meetha", "खट्टा": "khatta", "नमकीन": "namkeen", "तीखा": "teekha",
    "कच्चा": "kaccha", "पक्का": "pakka", "नकली": "nakli", "असली": "asli",
    "जिंदा": "zinda", "जीवित": "jeevit", "मुर्दा": "murda", "मृत": "mrit",
    "स्वस्थ": "swasth", "तंदरुस्त": "tandrust", "रोगी": "rogi", "अस्वस्थ": "aswasth",
    "भाग्यशाली": "bhagyashaali", "खुशनसीब": "khushnaseeb", "बदनसीब": "badnaseeb", "मनहूस": "manhoos",

    // ==========================================
    // 5. SLANG & DESI INTERNET LINGO
    // ==========================================
    "यार": "yaar", "भाई": "bhai", "ब्रो": "bro", "دوست": "dost",
    "बंदी": "bandi", "बंदा": "banda", "बाबू": "babu", "सोना": "sona",
    "बच्चा": "bacha", "किड": "kid", "अंकल": "uncle", "आंटी": "aunty",
    "पकाऊ": "pakau", "बकवास": "bakwaas", "फालतू": "faltu", "नल्ला": "nalla",
    "वेल्ला": "vella", "जुगाड़": "jugaad", "लोचा": "locha", "पंगा": "panga",
    "कांड": "kaand", "सीन": "scene", "लफड़ा": "lafla", "मैटर": "matter",
    "बिंदास": "bindaas", "धांसू": "dhansu", "कड़क": "kadak", "मस्त": "mast",
    "झकास": "jhakaas", "ओपी": "op", "लल": "lol", "रोफल": "rofl",
    "बेस्ट": "best", "वर्स्ट": "worst", "फेंकू": "fenku", "चेप": "chep",
    "चाटू": "chaatu", "चम्मच": "chamcha", "हवाबाजी": "hawabaazi", "नौटंकी": "nautanki",
    "ड्रामा": "drama", "ओवर": "over", "फुल": "full", "टाइट": "tight",
    "सॉर्टेड": "sorted", "सेट": "set", "चील": "chill", "कूल": "cool",
    "बवाल": "bawaal", "गदर": "gadar", "तबाही": "tabahi", "जहर": "zeher",
    "घंटा": "ghanta", "वाट": "waat", "बजा": "baja", "ठोक": "thok",
    "पेल": "pel", "सटक": "satak", "खिसक": "khisak", "निकल": "nikal",
    "कट": "kat", "चल": "chal", "फूट": "phoot", "रफा-दफा": "rafa-dafa",
    "चमका": "chamka", "समझा": "samjha", "बुझा": "bujha", "घुसा": "ghusa",
    "भेजा": "bheja", "खोपड़ी": "khopdi", "दिमाग": "dimaag", "बत्ती": "batti",
    "ट्यूबलाइट": "tubelight", "फट्टू": "fattu", "डरपोक": "darpok", "शेर": "sher",
    "चीता": "cheeta", "गुरु": "guru", "उस्ताद": "ustaad", "बॉस": "boss",
    "दादा": "dada", "भाईसाब": "bhaisaab", "मैडम": "madam", "सर": "sir",

    // ==========================================
    // 6. CONNECTORS & FILLERS (Conversation Glue)
    // ==========================================
    "मतलब": "matlab", "यानी": "yaani", "अर्थात": "arthaat", "जैसे": "jaise",
    "वैसे": "waise", "कैसे": "kaise", "ऐसे": "aise", "तैसे": "taise",
    "क्योंकि": "kyunki", "चूँकि": "chunke", "ताकि": "taaki", "जिससे": "jisse",
    "इसलिए": "isliye", "अत:": "atah", "लिहाज़ा": "lihaza", "फलस्वरूप": "falswaroop",
    "मगर": "magar", "किंतु": "kintu", "परंतु": "parantu", "बल्कि": "balki",
    "अगर": "agar", "यदि": "yadi", "काश": "kaash", "शायद": "shayad",
    "तभी": "tabhi", "अभी": "abhi", "कभी": "kabhi", "जब": "jab",
    "तब": "tab", "अब": "ab", "जहाँ": "jahan", "वहाँ": "wahan",
    "यहाँ": "yahan", "कहाँ": "kahan", "जिधर": "jidhar", "उधर": "udhar",
    "इधर": "idhar", "किधर": "kidhar", "हर्": "har", "प्रत्येक": "pratyek",
    "सब": "sab", "सारा": "saara", "पूरा": "poora", "कुल": "kul",
    "कुछ": "kuch", "थोड़ा": "thoda", "ज़रा": "zara", "अल्प": "alp",
    "ज्यादा": "zyada", "अधिक": "adhik", "बहुत": "bahut", "अत्यंत": "atyant",
    "कम": "kam", "न्यून": "nyun", "केवल": "keval", "मात्र": "matra",
    "सिर्फ": "sirf", "बस": "bas", "ही": "hi", "भी": "bhi",
    "तो": "toh", "तक": "tak", "भर": "bhar", "सा": "sa",
    "सी": "si", "से": "se", "वाला": "wala", "वाली": "wali",
    "वाले": "wale", "कर": "kar", "ने": "ne", "को": "ko",
    "के": "ke", "की": "ki", "का": "ka", "में": "mein",
    "पे": "pe", "पर": "par", "अरे": "are", "ओ": "oh",
    "वाह": "wah", "आह": "aah", "उफ़": "uff", "हाय": "haye",
    "छी": "chhee", "थू": "thoo", "धत": "dhat", "चल": "chal",
    // ==========================================
    // MALE NAMES (A-Z)
    // ==========================================
    "आरव": "Aarav", "आरुष": "Aarush", "आहान": "Aahan", "आदि": "Aadi",
    "आदित्य": "Aditya", "आकाश": "Aakash", "आमिर": "Aamir", "आसिफ": "Asif",
    "अभय": "Abhay", "अभिमन्यु": "Abhimanyu", "अभिनव": "Abhinav", "अभिषेक": "Abhishek",
    "अब्रार": "Abrar", "अदनान": "Adnan", "अजय": "Ajay", "अजीत": "Ajeet",
    "अकरम": "Akram", "अक्षय": "Akshay", "अक्षत": "Akshat", "अली": "Ali",
    "आलोक": "Alok", "अमन": "Aman", "अमर": "Amar", "अमित": "Amit",
    "अमजद": "Amjad", "अमोल": "Amol", "अमृत": "Amrit", "अनस": "Anas",
    "अनीस": "Anees", "अंगद": "Angad", "अनिल": "Anil", "अनिरुद्ध": "Anirudh",
    "अनीश": "Anish", "अंकित": "Ankit", "अंकुर": "Ankur", "अनमोल": "Anmol",
    "अंश": "Ansh", "अंशुमान": "Anshuman", "अनुज": "Anuj", "अनुपम": "Anupam",
    "अनुराग": "Anurag", "अरबाज": "Arbaaz", "अरशद": "Arshad", "अरुण": "Arun",
    "अरविंद": "Arvind", "आर्यन": "Aryan", "आशुतोष": "Ashutosh", "अश्विन": "Ashwin",
    "अतुल": "Atul", "अवनीश": "Avinash", "आयुष": "Ayush", "आजाद": "Azad",
    "अजीम": "Azeem", "अजहर": "Azhar", "अजीज": "Aziz",

    "बाबुल": "Babul", "बलबीर": "Balbir", "बलदेव": "Baldev", "बलविंदर": "Balwinder",
    "बंटी": "Bunty", "बिलाल": "Bilal", "बिरजू": "Birju", "बिस्वजीत": "Biswajit",
    "बृजेश": "Brijesh", "भगत": "Bhagat", "भरत": "Bharat", "भास्कर": "Bhaskar",
    "भावेश": "Bhavesh", "भूपेंद्र": "Bhupender", "भुवन": "Bhuvan", "भूषण": "Bhushan",

    "चंदन": "Chandan", "चंद्र": "Chandra", "चंद्रशेखर": "Chandrashekhar", "चरण": "Charan",
    "चेतन": "Chetan", "चिराग": "Chirag", "चिंटू": "Chintu", "चित्रेश": "Chitresh",

    "दानिश": "Danish", "दर्शन": "Darshan", "दया": "Daya", "दयानंद": "Dayanand",
    "दीपक": "Deepak", "दीपेश": "Deepesh", "देव": "Dev", "देवेंद्र": "Devendra",
    "देवेश": "Devesh", "धैर्य": "Dhairya", "धर्मेंद्र": "Dharmendra", "धवल": "Dhaval",
    "धीरज": "Dheeraj", "ध्रुव": "Dhruv", "दिग्विजय": "Digvijay", "दिलीप": "Dilip",
    "दिलशाद": "Dilshad", "दिनेश": "Dinesh", "दिवाकर": "Divyansh", "दुष्यंत": "Dushyant",

    "एहसान": "Ehsan", "एकलव्य": "Eklavya", "इलियास": "Elias",

    "फहाद": "Fahad", "फैसल": "Faisal", "फैजान": "Faizan", "फराज": "Faraz",
    "फरहान": "Farhan", "फरीद": "Farid", "फिरोज": "Firoz", "फुरकान": "Furkan",

    "गगन": "Gagan", "गजेंद्र": "Gajendra", "गणेश": "Ganesh", "गौरव": "Gaurav",
    "गौतम": "Gautam", "घनश्याम": "Ghanshyam", "गिरीश": "Girish", "गोपाल": "Gopal",
    "गोपी": "Gopi", "गोवर्धन": "Govardhan", "गोविंद": "Govind", "गुलशन": "Gulshan",
    "गुरदीप": "Gurdeep", "गुरमीत": "Gurmeet", "गुरप्रीत": "Gurpreet", "ज्ञान": "Gyan",

    "हबीब": "Habib", "हैदर": "Haider", "हमीद": "Hamid", "हनुमान": "Hanuman",
    "हार्दिक": "Hardik", "हरीश": "Harish", "हरजीत": "Harjeet", "हरमन": "Harman",
    "हर्ष": "Harsh", "हर्षद": "Harshad", "हर्षित": "Harshit", "हसन": "Hasan",
    "हेमंत": "Hemant", "हिमांशु": "Himanshu", "हितेश": "Hitesh", "हृितिक": "Hrithik",
    "हुसैन": "Hussain",

    "इब्राहिम": "Ibrahim", "इदरीस": "Idris", "इमरान": "Imran", "इंदर": "Inder",
    "इंद्रजीत": "Indrajeet", "इरफान": "Irfan", "इरशाद": "Irshad", "ईशान": "Ishaan",
    "ईश्वर": "Ishwar", "इस्माइल": "Ismail",

    "जगदीप": "Jagdeep", "जगदीश": "Jagdish", "जय": "Jai", "जयदीप": "Jaideep",
    "जमाल": "Jamal", "जमील": "Jameel", "जनक": "Janak", "जसबीर": "Jasbir",
    "जसप्रीत": "Jaspreet", "जावेद": "Javed", "जयंत": "Jayant", "जीतेन्द्र": "Jeetendra",
    "जिग्नेश": "Jignesh", "जितेन": "Jiten", "जुबैर": "Zubair", "जुनेद": "Junaid",

    "कबीर": "Kabir", "कैलाश": "Kailash", "कमल": "Kamal", "कमलेश": "Kamlesh",
    "कनक": "Kanak", "कन्हैया": "Kanhaiya", "कपिल": "Kapil", "करन": "Karan",
    "करम": "Karam", "कार्तिक": "Kartik", "करुण": "Karun", "काशी": "Kashi",
    "कौशल": "Kaushal", "कौशिक": "Kaushik", "केदार": "Kedar", "केशव": "Keshav",
    "केतन": "Ketan", "खालिद": "Khalid", "किरण": "Kiran", "किशन": "Kishan",
    "किशोर": "Kishore", "कृष्णा": "Krishna", "कुणाल": "Kunal", "कुंदन": "Kundan",
    "कुश": "Kush",

    "लक्ष्य": "Lakshya", "लखन": "Lakhan", "लक्ष्मण": "Laxman", "ललित": "Lalit",
    "लव": "Luv", "लक्की": "Lucky", "लोकेश": "Lokesh",

    "मदन": "Madan", "माधव": "Madhav", "महेंद्र": "Mahendra", "महेश": "Mahesh",
    "महिपाल": "Mahipal", "मजीद": "Majid", "मलिक": "Malik", "मानव": "Manav",
    "मंदीप": "Mandeep", "मंगल": "Mangal", "मंगेश": "Mangesh", "मणिकांत": "Manikant",
    "मनीष": "Manish", "मनजीत": "Manjeet", "मनमोहन": "Manmohan", "मनोज": "Manoj",
    "मनप्रीत": "Manpreet", "मंसूर": "Mansoor", "मनु": "Manu", "मयंक": "Mayank",
    "महरोज": "Mehroz", "मिहिर": "Mihir", "मिलिंद": "Milind", "मिराज": "Miraj",
    "मिथिलेश": "Mithilesh", "मोहम्मद": "Mohammad", "मोहन": "Mohan", "मोहित": "Mohit",
    "मोसीन": "Moshin", "मुबारक़": "Mubarak", "मुदस्सिर": "Mudassir", "मुकेश": "Mukesh",
    "मुकुंद": "Mukund", "मुनीर": "Muneer", "मुराद": "Murad", "मुश्ताक": "Mushtaq",
    "मुस्तफा": "Mustafa",

    "नदीम": "Nadeem", "नागराज": "Nagraj", "नकुल": "Nakul", "नमन": "Naman",
    "नंद": "Nand", "नंदन": "Nandan", "नारद": "Narad", "नारायण": "Narayan",
    "नरेंद्र": "Narendra", "नरेश": "Naresh", "नसीर": "Naseer", "नासिर": "Nasir",
    "नवीन": "Naveen", "नवेद": "Naved", "नवनीत": "Navneet", "नवाब": "Nawab",
    "नयन": "Nayan", "नील": "Neel", "नीरज": "Neeraj", "नेहल": "Nehal",
    "निखिल": "Nikhil", "निलेश": "Nilesh", "निमिष": "Nimish", "निरंजन": "Niranjan",
    "निर्मल": "Nirmal", "निशान्त": "Nishant", "नितीश": "Nitish", "नितिन": "Nitin",
    "नोमान": "Noman",

    "ओंकार": "Omkar", "ओस": "Ojas", "ओवैस": "Owais",

    "पंकज": "Pankaj", "परम": "Param", "परमजीत": "Paramjeet", "पारस": "Paras",
    "परेश": "Paresh", "पार्थ": "Parth", "परवेज": "Parvez", "पवन": "Pawan",
    "पीयूष": "Piyush", "प्रभाकर": "Prabhakar", "प्रभात": "Prabhat", "प्रभु": "Prabhu",
    "प्रबोध": "Prabodh", "प्रदीप": "Pradeep", "प्रफुल्ल": "Prafull", "प्रकाश": "Prakash",
    "प्रमोद": "Pramod", "प्राण": "Pran", "प्रणव": "Pranav", "प्रणय": "Pranay",
    "प्रसाद": "Prasad", "प्रशांत": "Prashant", "प्रसून": "Prasoon", "प्रतीक": "Prateek",
    "प्रवीण": "Praveen", "प्रेम": "Prem", "प्रीत": "Preet", "प्रीतम": "Pritam",
    "पृथ्वी": "Prithvi", "प्रियांक": "Priyank", "पुनीत": "Puneet", "पूरन": "Puran",
    "पुरुषोत्तम": "Purushottam", "पुष्कर": "Pushkar",

    "कासिम": "Qasim", "कादिर": "Qadir",

    "राघव": "Raghav", "रघु": "Raghu", "रहीम": "Rahim", "रहमान": "Rahman",
    "राहुल": "Rahul", "रजत": "Rajat", "राजीव": "Rajeev", "राजेंद्र": "Rajendra",
    "राजेश": "Rajesh", "राजू": "Raju", "राकेश": "Rakesh", "राम": "Ram",
    "रमन": "Raman", "रणबीर": "Ranbir", "रणदीप": "Randeep", "रंजीत": "Ranjeet",
    "रणवीर": "Ranveer", "राशिद": "Rashid", "रतन": "Ratan", "रवि": "Ravi",
    "रवींद्र": "Ravindra", "रज़ा": "Raza", "रयान": "Rehan", "रियाज़": "Riyaz",
    "रिहान": "Rihan", "ऋषि": "Rishi", "रितेश": "Ritesh", "ऋतिक": "Ritik",
    "रिज़वान": "Rizwan", "रोहन": "Rohan", "रोहित": "Rohit", "रोमिल": "Romil",
    "रोनक": "Ronak", "रोशन": "Roshan", "रुद्र": "Rudra", "रूपेश": "Rupesh",

    "सचिन": "Sachin", "सदाशिव": "Sadashiv", "सईद": "Saeed", "सागर": "Sagar",
    "साहिल": "Sahil", "साजिद": "Sajid", "सलीम": "Salim", "सलमान": "Salman",
    "समर": "Samar", "समीर": "Sameer", "संपत": "Sampat", "सैम": "Sam",
    "संदीप": "Sandeep", "संजय": "Sanjay", "संजीव": "Sanjeev", "संकेत": "Sanket",
    "संस्कार": "Sanskar", "संतोष": "Santosh", "सरफराज": "Sarfaraz", "सार्थक": "Sarthak",
    "सरवेश": "Sarvesh", "सतीश": "Satish", "सत्य": "Satya", "सत्येंद्र": "Satyendra",
    "सौरभ": "Saurabh", "सावन": "Savan", "शाहिद": "Shahid", "शाहरुख": "Shahrukh",
    "शैलेंद्र": "Shailendra", "शक्ति": "Shakti", "शम्मी": "Shammi", "शमशेर": "Shamsher",
    "शंकर": "Shankar", "शांतनु": "Shantanu", "शरद": "Sharad", "शशिकांत": "Shashikant",
    "शशांक": "Shashank", "शत्रुघ्न": "Shatrughan", "शौर्य": "Shaurya", "शेखर": "Shekhar",
    "शेर": "Sher", "शिखर": "Shikhar", "शिवा": "Shiva", "शिवाजी": "Shivaji",
    "शिवम": "Shivam", "शोएब": "Shoaib", "श्रवण": "Shravan", "श्रेयस": "Shreyas",
    "श्रीकांत": "Shrikant", "श्रीनिवास": "Shrinivas", "शुभम": "Shubham", "श्याम": "Shyam",
    "सिद्धार्थ": "Siddharth", "सिकंदर": "Sikandar", "सिमरन": "Simran", "सोहेल": "Sohail",
    "सोहन": "Sohan", "सोम": "Som", "सोमेश": "Somesh", "सोनू": "Sonu",
    "सौरव": "Sourav", "श्रीधर": "Sridhar", "सुभाष": "Subhash", "सुबोध": "Subodh",
    "सुदर्शन": "Sudarshan", "सुधीर": "Sudhir", "सुहैल": "Suhail", "सुजीत": "Sujeet",
    "सुखदेव": "Sukhdev", "सुखविंदर": "Sukhwinder", "सुल्तान": "Sultan", "सुमित": "Sumit",
    "सुंदर": "Sundar", "सुनील": "Sunil", "सन्नी": "Sunny", "सूरज": "Suraj",
    "सुरेंद्र": "Surendra", "सुरेश": "Suresh", "सूर्या": "Surya", "सुशांत": "Sushant",
    "सुशील": "Sushil", "स्वप्निल": "Swapnil", "सैयद": "Syed",

    "ताहिर": "Tahir", "तनिष्क": "Tanishq", "तनमय": "Tanmay", "तनवीर": "Tanveer",
    "तपन": "Tapan", "तारिक": "Tariq", "तरुण": "Tarun", "तेज": "Tej",
    "तेजस": "Tejas", "तिलक": "Tilak", "त्रिलोक": "Trilok", "तुषार": "Tushar",

    "उदय": "Uday", "उदित": "Udit", "उज्ज्वल": "Ujjwal", "उमंग": "Umang",
    "उमर": "Umar", "उमेश": "Umesh", "उत्कर्ष": "Utkarsh", "उत्तम": "Uttam",

    "वैभव": "Vaibhav", "वसीम": "Waseem", "वरुण": "Varun", "वेद": "Ved",
    "वेदांत": "Vedant", "वीर": "Veer", "वेंकटेश": "Venkatesh", "विभूति": "Vibhuti",
    "विक्की": "Vicky", "विजय": "Vijay", "विकास": "Vikas", "विक्रम": "Vikram",
    "विमल": "Vimal", "विनय": "Vinay", "विनीत": "Vineet", "विनोद": "Vinod",
    "विपिन": "Vipin", "विपुल": "Vipul", "विराट": "Virat", "विरेंद्र": "Virendra",
    "विशाल": "Vishal", "विशेष": "Vishesh", "विष्णु": "Vishnu", "विश्व": "Vishwa",
    "विश्वजीत": "Vishwajeet", "विवेक": "Vivek", "व्यास": "Vyas",

    "वहीद": "Waheed", "वारिस": "Waris", "वसीम": "Waseem",

    "यस": "Yash", "यज्ञ": "Yagya", "यक्ष": "Yaksh", "यशवंत": "Yashwant",
    "यतिन": "Yatin", "योगेश": "Yogesh", "युगल": "Yugal", "युवराज": "Yuvraj",

    "जहीद": "Zahid", "जैद": "Zaid", "जाकिर": "Zakir", "जीशान": "Zeeshan",

    // ==========================================
    // FEMALE NAMES (A-Z)
    // ==========================================
    "आंचल": "Aanchal", "आरती": "Aarti", "आभा": "Aabha", "आध्या": "Aadhya",
    "आकृति": "Aakriti", "आलिया": "Alia", "आमना": "Aamna", "आंचल": "Aanchal",
    "आशना": "Aashna", "आस्था": "Aastha", "आयात": "Aayat", "आभा": "Abha",
    "अदा": "Ada", "अदिति": "Aditi", "अफ़साना": "Afsana", "अफ़शीन": "Afsheen",
    "ऐश्वर्या": "Aishwarya", "आकांशा": "Akansha", "अक्षरा": "Akshara", "अलका": "Alka",
    "अल्पना": "Alpana", "अमीषा": "Amisha", "अमृता": "Amrita", "अमूल्या": "Amulya",
    "अनामिका": "Anamika", "आनंदी": "Anandi", "अनन्या": "Ananya", "अनीता": "Anita",
    "अंजलि": "Anjali", "अंजू": "Anju", "अंकिता": "Ankita", "अंशु": "Anshu",
    "अंतरा": "Antara", "अनु": "Anu", "अनुभा": "Anubha", "अनुपमा": "Anupama",
    "अनुराधा": "Anuradha", "अनुष्का": "Anushka", "अर्चना": "Archana", "आरज़ू": "Arzoo",
    "आशा": "Asha", "आशिमा": "Ashima", "अस्मिता": "Asmita", "अश्विनी": "Ashwini",
    "अवनी": "Avni", "आयशा": "Ayesha", "अज़रा": "Azra",

    "बबीता": "Babita", "बेबी": "Baby", "बरखा": "Barkha", "बसंती": "Basanti",
    "बेला": "Bela", "भक्ति": "Bhakti", "भानु": "Bhanu", "भावना": "Bhavna",
    "भूमिका": "Bhumika", "बिंदु": "Bindu", "बिपाशा": "Bipasha", "बुलबुल": "Bulbul",

    "चंचल": "Chanchal", "चांदनी": "Chandni", "चारु": "Charu", "छाया": "Chhaya",
    "चित्रा": "Chitra",

    "दामिनी": "Damini", "दर्पण": "Darpan", "दीक्षा": "Deeksha", "दीपा": "Deepa",
    "दीपाली": "Deepali", "दीपिका": "Deepika", "दीप्ति": "Deepti", "देविका": "Devika",
    "धारा": "Dhara", "दीया": "Diya", "दिपाली": "Dipali", "दिशा": "Disha",
    "दिव्या": "Divya", "दिव्यांशी": "Divyanshi", "डॉली": "Dolly", "दृष्टि": "Drishti",
    "दुर्गा": "Durga",

    "एकता": "Ekta", "ईशा": "Esha",

    "फराह": "Farah", "फरीदा": "Farida", "फरजाना": "Farzana", "फातिमा": "Fatima",
    "फिजा": "Fiza",

    "गार्गी": "Gargi", "गौरी": "Gauri", "गायत्री": "Gayatri", "गीता": "Geeta",
    "गीतांजलि": "Geetanjali", "गुंजन": "Gunjan", "गुरप्रीत": "Gurpreet",

    "हंसिका": "Hansika", "हरलीन": "Harleen", "हर्षिता": "Harshita", "हीना": "Heena",
    "हेमा": "Hema", "हेमलता": "Hemlata", "हिमानी": "Himani", "हिना": "Hina",

    "इला": "Ila", "इन्दु": "Indu", "इंद्राणी": "Indrani", "ईशानी": "Ishani",
    "इशिता": "Ishita", "इशरत": "Ishrat",

    "जाह्नवी": "Jahnavi", "जयश्री": "Jaishree", "जन्नत": "Jannat", "जसलीन": "Jasleen",
    "जसमीन": "Jasmin", "जया": "Jaya", "जीनत": "Zeenat", "झलक": "Jhalak",
    "जिया": "Jiya", "जूही": "Juhi", "ज्योति": "Jyoti", "ज्योत्सना": "Jyotsna",

    "काजल": "Kajal", "कला": "Kala", "कल्पना": "Kalpana", "कल्याणी": "Kalyani",
    "कामिनी": "Kamini", "कंचन": "Kanchan", "कनिका": "Kanika", "करीना": "Kareena",
    "करिश्मा": "Karishma", "करुणा": "Karuna", "कशिश": "Kashish", "कस्तूरी": "Kasturi",
    "काव्या": "Kavya", "कावेरी": "Kaveri", "कविता": "Kavita", "खुशबू": "Khushboo",
    "खुशी": "Khushi", "किरण": "Kiran", "कीर्ति": "Kirti", "किश्वर": "Kishwar",
    "कोमल": "Komal", "कोयल": "Koyal", "कृष्णा": "Krishna", "कृति": "Kriti",
    "कृतिका": "Kritika", "कुमुद": "Kumud", "कुसुम": "Kusum",

    "लाली": "Lali", "ललिता": "Lalita", "लारा": "Lara", "लता": "Lata",
    "लावण्या": "Lavanya", "लीला": "Leela", "लीना": "Leena", "लिली": "Lily",
    "लिपि": "Lipi",

    "माधवी": "Madhavi", "मधु": "Madhu", "मधुलिका": "Madhulika", "मधुमिता": "Madhumita",
    "माधुरी": "Madhuri", "महक": "Mahek", "माही": "Mahi", "महिमा": "Mahima",
    "मलाइका": "Malaika", "मालती": "Malti", "मालविका": "Malvika", "ममता": "Mamta",
    "मानसी": "Manasi", "मनीषा": "Manisha", "मंजू": "Manju", "मंजुला": "Manjula",
    "मन्न": "Mannat", "मनोरमा": "Manorama", "मानवी": "Manvi", "मान्या": "Manya",
    "मरियम": "Mariyam", "माया": "Maya", "मयूरी": "Mayuri", "मेधा": "Medha",
    "मीना": "Meena", "मीनाक्षी": "Meenakshi", "मीरा": "Meera", "मेघा": "Megha",
    "मेहर": "Meher", "मीनू": "Minu", "मिष्टी": "Mishti", "मोहिनी": "Mohini",
    "मोना": "Mona", "मोनिका": "Monica", "मृदुला": "Mridula", "मुक्ता": "Mukta",
    "मुस्कान": "Muskan",

    "नादिया": "Nadia", "नैना": "Naina", "नलिनी": "Nalini", "नमिता": "Namita",
    "नंदिनी": "Nandini", "नंदिता": "Nandita", "नर्गिस": "Nargis", "नताशा": "Natasha",
    "नीलिमा": "Neelima", "नीलू": "Neelu", "नीतू": "Neetu", "नेहा": "Neha",
    "नेत्रा": "Netra", "निधि": "Nidhi", "निकी": "Niki", "निकिता": "Nikita",
    "नीलम": "Nilam", "नीलिमा": "Nilima", "निम्मी": "Nimmi", "निरूपा": "Nirupa",
    "निरुपमा": "Nirupama", "निशा": "Nisha", "निशि": "Nishi", "निधि": "Nidhi",
    "निवेदिता": "Nivedita", "नियत": "Niyati", "नूर": "Noor", "नूतन": "Nutan",

    "पलक": "Palak", "पल्लवी": "Pallavi", "पम्मी": "Pammi", "परि": "Pari",
    "परिणीति": "Parineeti", "पारुल": "Parul", "पार्वती": "Parvati", "परवीन": "Parveen",
    "पायल": "Payal", "पिंकी": "Pinky", "पूजा": "Pooja", "पूनम": "Poonam",
    "पूर्वा": "Poorva", "प्रभा": "Prabha", "प्रज्ञा": "Pragya", "प्रणाली": "Pranali",
    "प्रतिभा": "Pratibha", "प्रतीक्षा": "Pratiksha", "प्रीति": "Preeti", "प्रेरणा": "Prerna",
    "प्रिया": "Priya", "प्रियंका": "Priyanka", "पूर्वी": "Purvi", "पुष्पा": "Pushpa",

    "रचना": "Rachna", "राधा": "Radha", "राधिका": "Radhika", "रागिनी": "Ragini",
    "राजश्री": "Rajshree", "रक्खी": "Rakhi", "रक्षा": "Raksha", "रमा": "Rama",
    "रम्य": "Ramya", "रानी": "Rani", "रंजना": "Ranjana", "रश्मि": "Rashmi",
    "रवीना": "Raveena", "रेखा": "Rekha", "रेणु": "Renu", "रेणुका": "Renuka",
    "रेशमा": "Reshma", "रेवती": "Revati", "ऋचा": "Richa", "रिद्धि": "Riddhi",
    "रिम्पी": "Rimpi", "रिंकू": "Rinku", "ऋषि": "Rishi", "रीतिका": "Ritika",
    "रितु": "Ritu", "रिया": "Riya", "रोहिणी": "Rohini", "रोमा": "Roma",
    "रोशनी": "Roshni", "रूबी": "Ruby", "रुचि": "Ruchi", "रुही": "Ruhi",
    "रुकसाना": "Ruksana", "रूपा": "Rupa", "रूपाली": "Rupali",

    "सबा": "Saba", "साधना": "Sadhana", "साक्षी": "Sakshi", "सलमा": "Salma",
    "सलोनी": "Saloni", "समिक्षा": "Samiksha", "समीरा": "Sameera", "सना": "Sana",
    "संध्या": "Sandhya", "संगीता": "Sangeeta", "संजना": "Sanjana", "संजू": "Sanju",
    "संतोष": "Santosh", "सान्या": "Sanya", "सपना": "Sapna", "सारा": "Sara",
    "सरगम": "Sargam", "सरिता": "Sarita", "सरोज": "Saroj", "सविता": "Savita",
    "सायरा": "Sayara", "सीमा": "Seema", "सेजल": "Sejal", "शबनम": "Shabnam",
    "शगुफ्ता": "Shagufta", "शगुन": "Shagun", "शालिनी": "Shalini", "शमाइला": "Shamaila",
    "शमीम": "Shamim", "शन्नो": "Shanno", "शांति": "Shanti", "शन्या": "Shanya",
    "शारदा": "Sharda", "शर्मीला": "Sharmila", "शशी": "Shashi", "शीबा": "Sheeba",
    "शीला": "Sheela", "शीतल": "Sheetal", "शेफाली": "Shefali", "शिखा": "Shikha",
    "शिल्पा": "Shilpa", "शिवांगी": "Shivangi", "शिवानी": "Shivani", "शोभा": "Shobha",
    "शोभना": "Shobhana", "श्रद्धा": "Shraddha", "श्रेया": "Shreya", "श्रुति": "Shruti",
    "शुभ्रा": "Shubhra", "श्वेता": "Shweta", "सिद्दी": "Siddhi", "सिमरन": "Simran",
    "सिंधु": "Sindhu", "स्मिता": "Smita", "स्मृति": "Smriti", "स्नेहा": "Sneha",
    "स्नेहल": "Snehal", "सोहा": "Soha", "सोमा": "Soma", "सोना": "Sona",
    "सोनाक्षी": "Sonakshi", "सोनाली": "Sonali", "सोनम": "Sonam", "सोनिया": "Sonia",
    "सौम्या": "Soumya", "सृष्टि": "Srishti", "सुभा": "Subha", "सुधा": "Sudha",
    "सुहासिनी": "Suhasini", "सुजाता": "Sujata", "सुमन": "Suman", "सुमित्रा": "Sumitra",
    "सुनैना": "Sunaina", "सुनिधि": "Sunidhi", "सुनीता": "Sunita", "सुप्रिया": "Supriya",
    "सुरभि": "Surbhi", "सुषमा": "Sushma", "सुस्मिता": "Sushmita", "स्वाति": "Swati",

    "तब्बू": "Tabbu", "तनीषा": "Tanisha", "तन्वी": "Tanvi", "तनु": "Tanu",
    "तनुजा": "Tanuja", "तारा": "Tara", "तस्नीम": "Tasneem", "तेजल": "Tejal",
    "टीना": "Tina", "तृप्ति": "Tripti", "तूलिका": "Tulika", "ट्विंकल": "Twinkle",

    "उमा": "Uma", "उमरा": "Umra", "उन्नति": "Unnati", "उपासना": "Upasana",
    "उर्मिला": "Urmila", "उर्वशी": "Urvashi", "उषा": "Usha",

    "वैदेही": "Vaidehi", "वैशाली": "Vaishali", "वंदना": "Vandana", "वाणी": "Vani",
    "वंशिता": "Vanshita", "वर्षा": "Varsha", "वसुधा": "Vasudha", "वीणा": "Veena",
    "विभा": "Vibha", "विद्या": "Vidya", "विजेता": "Vijeta", "विमी": "Vimi",
    "विनीता": "Vinita", "विपाशा": "Vipasha", "विशाखा": "Vishakha", "वृंदा": "Vrinda",

    "यामिनी": "Yamini", "याशिका": "Yashika", "यशी": "Yashi", "युक्ति": "Yukti",

    "ज़ारा": "Zara", "ज़रीन": "Zareen", "ज़ोया": "Zoya", "ज़ुबिया": "Zubiya"

};

module.exports = commonHinglishMap;
